name: kglab
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.6
  - pip
  - fsspec[gs,s3] >= 0.8.5
  - gcsfs >= 0.7.1
  - gensim >= 3.8.3
  - matplotlib >= 3.3.4
  - networkx >= 2.5
  - numpy >= 1.19.4
  - owlrl >= 5.2.1
  - pandas >= 1.1.5
  - pyarrow >= 2.0.0
  - pylev >= 1.3
  - pynvml >= 8.0.4
  - pyshacl >= 0.14.2
  - python-dateutil >= 2.8
  - pyvis >= 0.1.7
  - requests >= 2.25.1
  - rdflib >= 5.0.0
  - rdflib-jsonld >= 0.5.0
  - scikit-learn >= 0.20.2
  - statsmodels >= 0.12
  - tqdm >= 4.56
  - pip:
    - chocolate >= 0.0.2
    - csvwlib >= 0.3.2
    - icecream >= 2.0
    - pslpython >= 2.2.2
    - torch >= 1.8
    - urlpath >= 1.1.7
